spring.application.name=lter_xml_simulator

#spring.path.eqname=${path.eqname}
#spring.path.date=${path.date}


#spring.path.sample.base=/data4/lter_sim/sample_xml/csm/log/pm/ossraw/
spring.path.sample.base=/Users/hyobin/Desktop/workspace/spring_projects/lter_xml_simulator/src/main/resources/
#spring.path.destination.base=/data4/lter_sim/sample_xml/csm/log/pm/ossraw/
spring.path.destination.base=/Users/hyobin/Desktop/workspace/spring_projects/lter_xml_simulator/src/main/resources/

spring.path.eqname=PS1_CSCF01
spring.path.date=20220812

# 1?? ???? ?????.
# 5 minutes -> 1hour ?
#
